language: php
sudo: false
dist: trusty
php:
  - 7.2
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
before_script:
  - composer self-update
  - composer update --prefer-lowest --prefer-stable
script:
  - ./vendor/bin/phpunit --coverage-clover=coverage.clover
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage.clover
